export const FETCH_SEARCH_OPTIONS = 'FETCH_SEARCH_OPTIONS';
export const FETCH_WEATHER_FOR_WOEID = 'FETCH_WEATHER_FOR_WOEID';

export const FETCH_SEARCH_OPTIONS_READY = 'FETCH_SEARCH_OPTIONS_READY';
export const FETCH_SEARCH_OPTIONS_IN_PROGRESS = 'FETCH_SEARCH_OPTIONS_IN_PROGRESS';
export const FETCH_SEARCH_OPTIONS_SUCCESS = 'FETCH_SEARCH_OPTIONS_SUCCESS';
export const FETCH_SEARCH_OPTIONS_FAILURE = 'FETCH_SEARCH_OPTIONS_FAILURE';

export const FETCH_WEATHER_FOR_WOEID_READY = 'FETCH_WEATHER_FOR_WOEID_READY';
export const FETCH_WEATHER_FOR_WOEID_IN_PROGRESS = 'FETCH_WEATHER_FOR_WOEID_IN_PROGRESS';
export const FETCH_WEATHER_FOR_WOEID_SUCCESS = 'FETCH_WEATHER_FOR_WOEID_SUCCESS';
export const FETCH_WEATHER_FOR_WOEID_FAILURE = 'FETCH_WEATHER_FOR_WOEID_FAILURE';

export const UNIT_TOGGLE = 'UNIT_TOGGLE';
export const RESET_WEATHER_DATA_AND_STATUS = 'RESET_WEATHER_DATA_AND_STATUS';
